### ISSUE TITLE
trying to build with gcc / linux

### ISSUE THREAD

**Issue by mhaberler** [chai2010/protorpc.cxx#1]
nice package; would be great to build on linux, but minor issue:

mah@nwheezy:~/src/protorpc.cxx/build$ gcc --version
gcc (Debian 4.7.2-5) 4.7.2

needed this:
//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=-std=gnu++11

getting this - please advise:

[  0%] Building CXX object CMakeFiles/pblib.dir/src/google/protobuf/rpc/rpc_server.o
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc: In member function ‘void google::protobuf::rpc::Server::AddService(google::protobuf::rpc::Service_, bool)’:
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc:39:50: error: expected ‘<’ before ‘<:’ token
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc:39:50: error: expected type-specifier before ‘<:’ token
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc:39:50: error: expected ‘>’ before ‘<:’ token
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc:39:50: error: expected ‘(’ before ‘<:’ token
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc:39:52: error: expected identifier before ‘:’ token
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc:39:97: error: expected ‘]’ before ‘;’ token
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc: In lambda function:
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc:39:97: error: expected ‘{’ before ‘;’ token
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc: In member function ‘void google::protobuf::rpc::Server::AddService(google::protobuf::rpc::Service_, bool)’:
/home/mah/src/protorpc.cxx/src/google/protobuf/rpc/rpc_server.cc:39:97: error: expected ‘)’ before ‘;’ token
make[2]: **\* [CMakeFiles/pblib.dir/src/google/protobuf/rpc/rpc_server.o] Error 1

**Comment by chai2010** [comment]
You can try only copy XmlMessage files first:
https://github.com/chai2010/protorpc.cxx/tree/master/src/google/protobuf/xml

Or, can your give a path for linux build(i have no linux)?
Thanks!

**Comment by mhaberler** [comment]
the only change needed is an extra space, gcc is picky:

https://github.com/chai2010/protorpc.cxx/blob/master/src/google/protobuf/rpc/rpc_server.cc#L39

inser a space after '<':

```
service_method_map_[method_name] = const_cast< ::google::protobuf::MethodDescriptor*>(method);
```
